### ISSUE TITLE
ERROR: Could not build wheels for flashlight-sequence, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by asadullah797** [flashlight/sequence#16]
(base) [22204840@login2 sequence]$ python3 -m pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/people/22204840/fair/fairseq/sequence
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: flashlight-sequence
  Building wheel for flashlight-sequence (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for flashlight-sequence (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying bindings/python/flashlight/lib/sequence/version.py -> build/lib.linux-x86_64-cpython-311/flashlight/lib/sequence
      running build_ext
      CMake Error at /tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
      Call Stack (most recent call first):
        /tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        /tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindOpenMP.cmake:577 (find_package_handle_standard_args)
        flashlight/lib/sequence/criterion/CMakeLists.txt:4 (find_package)
        flashlight/lib/sequence/CMakeLists.txt:3 (include)
        CMakeLists.txt:74 (include)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/opt/software/python/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/software/python/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/software/python/3.11.3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 184, in <module>
        File "<string>", line 150, in main
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-fkb3dz2o/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 82, in run
        File "<string>", line 126, in build_extensions
        File "/opt/software/python/3.11.3/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/people/22204840/fair/fairseq/sequence', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/people/22204840/fair/fairseq/sequence/build/lib.linux-x86_64-cpython-311/flashlight/lib/sequence', '-DPython3_EXECUTABLE=/opt/software/python/3.11.3/bin/python3', '-DBUILD_SHARED_LIBS=ON', '-DFL_SEQUENCE_BUILD_TESTS=OFF', '-DFL_SEQUENCE_BUILD_PYTHON=ON', '-DFL_SEQUENCE_BUILD_PYTHON_PACKAGE=ON', '-DFL_SEQUENCE_BUILD_STANDALONE=OFF', '-DFL_SEQUENCE_USE_OPENMP=ON', '-DFL_SEQUENCE_USE_CUDA=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flashlight-sequence
Failed to build flashlight-sequence
ERROR: Could not build wheels for flashlight-sequence, which is required to install pyproject.toml-based projects

**Comment by jacobkahn** [comment]
@asadullah797 -- the build here can't find OpenMP. You can set `USE_OPENMP=OFF` s an environment variable as described in the documentation, or you can install OpenMP. 

It should be available with your Python interpreter though; which Python version are you using and on which platform?

**Comment by jacobkahn** [comment]
Closing due to inactivity.
